import Link from "next/link";
import { ArrowUpRight, ArrowRight, Radio, Bell, WalletCards } from "lucide-react";
import Brand from "@/components/brand";
import Demo from "@/components/demo";

export default function Home(){return <main className="marketing">
<header className="marketing-nav row between"><Brand/><nav><a href="#product">Product</a><a href="#how-it-works">How it works</a><a href="#pricing">Pricing</a></nav><div className="row"><Link href="/login" className="muted">Sign in</Link><Link className="button primary" href="/signup">Start monitoring <ArrowUpRight size={15}/></Link></div></header>
<section className="hero"><div><span className="tag"><Radio size={13}/> YOUR NEXT CUSTOMER IS ALREADY TALKING</span><h1>Find the conversations<br/><span>worth joining.</span></h1><p>Monitor X for the conversations that matter to your business. Find the opportunity, understand the context, and join while it’s still fresh.</p><div className="row"><Link href="/signup" className="button primary">Start monitoring <ArrowRight size={16}/></Link><a href="#how-it-works" className="button quiet">See how it works</a></div><p className="footnote">Usage-based. No subscription. You control every radar’s scan budget.</p></div><Demo/></section>
<section id="product" className="marketing-section"><span className="eyebrow">LESS SEARCHING. BETTER TIMING.</span><h2>The right conversation.<br/>Before everyone else gets there.</h2><p className="muted" style={{maxWidth:620}}>Someone is asking for exactly what you’re building. ReplyRadar keeps watch, filters weak matches, and brings the useful conversations into one inbox.</p><div className="grid2"><div className="panel"><span className="eyebrow">01 / LISTEN WITH INTENT</span><h3 style={{marginTop:18}}>Turn a signal into a search.</h3><div className="query mono">vercel (expensive OR pricing OR bill OR alternative)<br/>-is:retweet</div><p className="muted">Competitor pain, recommendation requests, brand mentions, or your next customer.</p></div><div className="panel"><span className="eyebrow">02 / CONTROL THE SPEND</span><h3 style={{marginTop:18}}>One request. Your result cap.</h3><p className="muted">Each scan is capped to a single X Recent Search request. Set a 10–100 post ceiling per radar, and monitoring pauses automatically when your credits reach zero.</p></div></div></section>
<section id="how-it-works" className="marketing-section"><span className="eyebrow">FROM SEARCH TO CONVERSATION</span><h2>Set your radar. Keep shipping.</h2><div className="steps">{[["Define the conversation","Describe what matters, then fine-tune your query, active hours, score threshold, and result cap."],["Let your radar listen","Background scans discover, deduplicate, score, and discard weak results before they reach your inbox."],["Join when it matters","See new matches in ReplyRadar, open the original X post, and reply yourself."]].map(([title,copy],i)=><div className="panel" key={title}><div className="step-num">0{i+1} ─────────</div><h3>{title}</h3><p>{copy}</p></div>)}</div></section>
<section className="marketing-section"><div className="row between wrap"><div><span className="eyebrow">BUILT-IN SIGNAL INBOX</span><h2>Notifications stay in ReplyRadar.</h2><p className="muted">No Telegram setup. No Discord webhook. No email integration.<br/>New high-quality matches appear in your notification center.</p></div><div className="row wrap"><span className="button"><Bell size={18}/> In-app notifications</span><span className="button"><WalletCards size={18}/> Prepaid credits</span></div></div></section>
<section id="pricing" className="marketing-section"><span className="eyebrow">PAY FOR USAGE, NOT A PLAN.</span><h2>Buy credits. Spend them only when you scan.</h2><p className="muted">No subscription and no automatic renewal. Choose a credit pack, set per-radar result caps, and monitor your exact spend inside ReplyRadar.</p><div className="pricing">{[10,25,50,100].map((amount,i)=><div className={"panel "+(amount===25?"featured":"")} key={amount}><span className="eyebrow">CREDIT PACK</span><div className="price">${amount}<small> prepaid</small></div><ul><li>No expiration while your account is active</li><li>Shared across all radars</li><li>Per-radar scan cost controls</li><li>Auto-pause at zero balance</li></ul><Link href="/signup" className={"button "+(amount===25?"primary":"quiet")} style={{width:"100%"}}>Get started <ArrowUpRight size={14}/></Link></div>)}</div></section>
<footer className="footer row between wrap"><Brand/><span>Find the signal. Pay for the search. Write the reply.</span><Link href="/login">Sign in →</Link></footer>
</main>}
