"use client";
import { useEffect,useState } from "react";
import { ArrowUpRight,Archive,VolumeX,X } from "lucide-react";

const ago=(v:string)=>{const s=Math.max(0,Math.floor((Date.now()-+new Date(v))/1000));return s<60?`${s}s ago`:s<3600?`${Math.floor(s/60)}m ago`:s<86400?`${Math.floor(s/3600)}h ago`:`${Math.floor(s/86400)}d ago`};
async function api(path:string,method="GET",body?:unknown){const r=await fetch("/api/app/"+path,{method,headers:method==="GET"?{}:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined,cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");return d}

export default function MatchesUI(){
 const [data,setData]=useState<any>(null),[filter,setFilter]=useState("all"),[score,setScore]=useState("0"),[page,setPage]=useState(0),[detail,setDetail]=useState<any>(null),[msg,setMsg]=useState("");
 async function load(){try{setData(await api("matches?"+new URLSearchParams({filter,score,page:String(page)})));setMsg("")}catch(e){setMsg((e as Error).message)}}
 useEffect(()=>{void load();const t=setInterval(load,10000);return()=>clearInterval(t)},[filter,score,page]);
 async function action(m:any,verb:string){try{await api(`matches/${m.id}/${verb}`,"POST",verb==="archive"?{archived:!m.archived_at}:{});setDetail(null);await load()}catch(e){setMsg((e as Error).message)}}
 return <><div className="page-head"><h1>Matches</h1><p>Only conversations that clear your radar’s score threshold are kept.</p></div>{msg&&<div className="notice">{msg}</div>}<div className="row wrap" style={{marginBottom:18}}><select value={filter} onChange={e=>{setFilter(e.target.value);setPage(0)}}><option value="all">All active</option><option value="high">High opportunity</option><option value="BUYING_INTENT">Buying intent</option><option value="RECOMMENDATION_REQUEST">Recommendation requests</option><option value="COMPLAINT">Complaints</option><option value="QUESTION">Questions</option><option value="archived">Archived</option></select><select value={score} onChange={e=>{setScore(e.target.value);setPage(0)}}><option value="0">Any score</option><option value="70">70+</option><option value="80">80+</option><option value="90">90+</option></select></div>
 <div className="panel" style={{padding:"0 20px"}}>{data?.items?.length?data.items.map((m:any)=><article className="match" key={m.id}><button className="score" onClick={()=>setDetail(m)}><span>{m.score}<small>SCORE</small></span></button><div><div className="row between wrap"><div><strong>{m.display_name||m.username}</strong> <span className="muted">@{m.username}</span></div><span className="muted" style={{fontSize:11}}>{ago(m.posted_at)}</span></div><p>{m.text}</p><div className="match-meta"><span>{m.likes} likes</span><span>{m.replies} replies</span><span>{m.reposts} reposts</span><span>{m.radar_name}</span></div><div className="match-actions"><a className="button primary" href={m.url} target="_blank" rel="noreferrer">Open on X <ArrowUpRight size={13}/></a><button className="quiet" onClick={()=>setDetail(m)}>Details</button><button className="quiet" onClick={()=>action(m,"archive")}><Archive size={13}/>{m.archived_at?"Restore":"Archive"}</button><button className="quiet" onClick={()=>action(m,"mute")}><VolumeX size={13}/>Mute author</button></div></div></article>):data?<div className="empty"><h2>No matches here yet.</h2><p>New qualified conversations appear after a successful scan.</p></div>:<div className="loading">Loading conversations…</div>}</div>
 <div className="row between" style={{marginTop:20}}><button disabled={page===0} onClick={()=>setPage(page-1)}>Previous</button><span className="muted">Page {page+1}</span><button disabled={!data?.more} onClick={()=>setPage(page+1)}>Next</button></div>
 {detail&&<div className="drawer-backdrop" onClick={()=>setDetail(null)}><div className="drawer" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><div className="row between"><h2>Conversation detail</h2><button onClick={()=>setDetail(null)}><X size={17}/></button></div><span className="tag">{detail.score} / 100 opportunity</span><h3 style={{marginTop:25}}>@{detail.username}</h3><p>{detail.text}</p><p className="muted">{detail.likes} likes · {detail.replies} replies · {detail.followers} followers</p><a className="button primary" href={detail.url} target="_blank" rel="noreferrer">Open on X <ArrowUpRight size={15}/></a><h3 style={{marginTop:30}}>Why this scored {detail.score}</h3>{Object.entries(detail.score_breakdown_json||{}).map(([k,v])=><div className="breakdown-row" key={k}><span>{k}</span><span>{String(v)}</span></div>)}<h3>Matched radar · {detail.radar_name}</h3><div className="query mono">{detail.query}</div><p className="muted" style={{marginTop:20}}>This match is also available in your in-app notification center. ReplyRadar does not send it through external channels.</p></div></div>}
 </>;
}
