import { z } from "zod";
export const PLANS = {
  free: { price: 0, radars: 50, interval: 600, scans: 1000000 },
  starter: { price: 0, radars: 50, interval: 600, scans: 1000000 },
  pro: { price: 0, radars: 50, interval: 600, scans: 1000000 },
  growth: { price: 0, radars: 50, interval: 600, scans: 1000000 },
} as const;
export type Plan = keyof typeof PLANS;
export function entitlement(_s?: { plan: string; status: string; current_period_end?: string | Date | null }) { return "free" as Plan; }
export const scheduleSchema=z.object({days:z.array(z.number().int().min(0).max(6)).min(1).max(7),start:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),end:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/)}).nullable();
export type Schedule=z.infer<typeof scheduleSchema>;
export function inSchedule(date:Date,timezone:string,schedule:Schedule){if(!schedule)return true;const p=new Intl.DateTimeFormat("en-US",{timeZone:timezone,weekday:"short",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date);const value=(t:string)=>p.find(v=>v.type===t)!.value;const day=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(value("weekday"));const time=value("hour")+":"+value("minute");if(schedule.start===schedule.end)return schedule.days.includes(day);if(schedule.start<schedule.end)return schedule.days.includes(day)&&time>=schedule.start&&time<schedule.end;return(schedule.days.includes(day)&&time>=schedule.start)||(schedule.days.includes((day+6)%7)&&time<schedule.end);}
export function validateQuery(query:string){if(query.trim().length<2||query.length>512)throw new Error("Use a query between 2 and 512 characters.");if((query.match(/"/g)||[]).length%2)throw new Error("Close the quotation marks in your query.");let depth=0;for(const c of query){if(c==="(")depth++;if(c===")"&&--depth<0)throw new Error("Check the parentheses in your query.");}if(depth)throw new Error("Check the parentheses in your query.");return query.trim();}
export const radarSchema=z.object({name:z.string().trim().min(2).max(80),description:z.string().max(1000).default(""),query:z.string().transform((v,ctx)=>{try{return validateQuery(v)}catch(e){ctx.addIssue({code:"custom",message:(e as Error).message});return z.NEVER}}),enabled:z.boolean().default(true),scan_interval_seconds:z.number().int().min(600).max(86400),timezone:z.string().refine(v=>{try{new Intl.DateTimeFormat("en",{timeZone:v});return true}catch{return false}},"Use a valid IANA timezone"),active_schedule_json:scheduleSchema.default(null),minimum_score:z.number().int().min(0).max(100).default(70),integration_ids:z.array(z.uuid()).max(20).default([])});
export type SocialPost={externalId:string;platform:"x";authorId:string;username:string;displayName?:string;text:string;url:string;createdAt:Date;metrics:{likes:number;replies:number;reposts:number;quotes:number};author:{followers:number;verified:boolean}};
export function scorePost(p:SocialPost,now=new Date()){const age=Math.max(1,(+now-+p.createdAt)/60000),engagement=p.metrics.likes+p.metrics.reposts*2+p.metrics.quotes*2+p.metrics.replies;const t=p.text.toLowerCase();const intent=/looking for|need a|budget|buy|pay for/.test(t)?"BUYING_INTENT":/recommend|alternative|what do you use/.test(t)?"RECOMMENDATION_REQUEST":/expensive|frustrat|broken|hate|bill/.test(t)?"COMPLAINT":t.includes("?")?"QUESTION":/versus|competitor/.test(t)?"COMPETITOR_MENTION":/@\w+/.test(t)?"BRAND_MENTION":"GENERAL_DISCUSSION";const components={freshness:Math.round(30*Math.exp(-age/90)),velocity:Math.round(Math.min(25,Math.log1p(engagement/age)*7)),intent:["BUYING_INTENT","RECOMMENDATION_REQUEST"].includes(intent)?25:intent==="GENERAL_DISCUSSION"?5:17,saturation:Math.round(10/(1+p.metrics.replies/12)),reach:Math.round(Math.min(10,Math.log10(1+p.author.followers)*2))};return{score:Object.values(components).reduce((a,b)=>a+b,0),intent,components};}
export function suggestQuery(description:string,goal="customers"){const words=description.toLowerCase().replace(/[^a-z0-9 @-]/g,"").split(/\s+/).filter(w=>w.length>2&&!['people','looking','about','being','that','with','want','find','for','the','are','and','complaining'].includes(w));const topic=words.slice(0,3).join(" ")||"deployment";if(/vercel/i.test(description))return"vercel (expensive OR pricing OR bill OR alternative) -is:retweet";return goal==="brand"?`"${topic}" -is:retweet`:`("looking for" OR recommend OR alternative) "${topic}" -is:retweet`;}
